# Generated by Django 2.0.9 on 2020-06-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=128, unique=True)),
                ('seller_password', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
