# Generated by Django 2.0.9 on 2020-06-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_item', '0002_auto_20200601_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
