# Generated by Django 2.0.9 on 2020-06-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_item', '0003_auto_20200625_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='spu',
            name='spu_status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='goods_id',
            field=models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='db_item.Goods', verbose_name='商品id'),
        ),
    ]
